version: "3.3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - "./instaPic-backend/db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
    container_name: dbinstapic
  api:
    build: 
      context: ./instaPic-backend
      args:
        API_PATH: ${API_PATH}
    depends_on:
      - db
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    container_name: backendinstapic
    command: bash -c "sleep 7 && npm start"
  web:
    build: 
      context: ./instapic-frontend
      args:
        REACT_APP_API_PORT: ${REACT_APP_API_PORT}
        REACT_APP_API_HOST: ${REACT_APP_API_HOST}
        REACT_APP_WEB_PATH: ${REACT_APP_WEB_PATH}
    depends_on:
      - db
      - api
    expose:
      - ${REACT_APP_WEB_PORT}
    ports:
      - ${REACT_APP_WEB_PORT}:${REACT_APP_WEB_PORT}
    container_name: frontendinstapic
    command: bash -c "serve -s build"
    
