version: "3.3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - "./instaPic-backend/db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
    container_name: dbinstapic
  api:
    build: ./instaPic-backend
    depends_on:
      - db
    working_dir: ${API_PATH}
    ports:
      - ${API_PORT}:${API_PORT}
    expose:
      - ${API_PORT}
    container_name: backendinstapic
    command: bash -c "sleep 10 && npm start"
